apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: web
  labels:
    app: nginx-demo
spec:
  type: LoadBalancer
  selector:
    app: nginx-demo
  ports:
    - name: http
      port: 80
      targetPort: 80

