apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "nginx-demo.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80

